ToDo/Models/Arguments/Item/InsertItemRequest.cs
namespace ToDo.Models.Arguments.Item
{
    public class InsertItemRequest 
    {
        public string Description { get; set; }
        public int Position { get; set; }
        public int IdListItem { get; set; }
        public int? IdParentItem { get; set; }
    }
}

ToDo/Models/Arguments/Item/InsertItemResponse.cs
namespace ToDo.Models.Arguments.Item
{
    public class InsertItemResponse
    {
        public int Id { get; set; }
        public string Message { get; set; }
    }
}

ToDo/Models/Arguments/Item/ItemResponse.cs
namespace ToDo.Models.Arguments.Item
{
    public class ItemResponse
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int Position { get; set; }
        public int IdListItem { get; set; }
        public int? IdParentItem { get; set; }
    }
}

ToDo/Models/Arguments/Item/RemoveItemResponse.cs
namespace ToDo.Models.Arguments.Item
{
    public class RemoveItemResponse
    {
        public string Message { get; set; }
    }
}

ToDo/Models/Arguments/Item/UpdateItemRequest.cs
using System;

namespace ToDo.Models.Arguments.Item
{
    public class UpdateItemRequest
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int Position { get; set; }
        public int? IdParentItem { get; set; }

        public static explicit operator UpdateItemRequest(ItemResponse item)
        {
            return new UpdateItemRequest()
            {
                Id = item.Id,
                Description = item.Description,
                Position = item.Position,
                IdParentItem = item.IdParentItem
            };
        }
    }
}

ToDo/Models/Arguments/Item/UpdateItemResponse.cs
namespace ToDo.Models.Arguments.Item
{
    public class UpdateItemResponse
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int Position { get; set; }
        public int? IdParentItem { get; set; }

        public string Message { get; set; }
    }
}

ToDo/Controllers/ItemController.cs
using System;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web.Mvc;
using ToDo.Models.Arguments.Item;
using ToDo.ServicesApi;
using ToDo.Utils;

namespace ToDo.Controllers
{
    public class ItemController : Controller
    {
        public int IdList
        {
            get
            {
                return int.Parse(Session["IdList"].ToString());
            }
            set
            {
                Session["IdList"] = value;
            }
        }

        private readonly IServiceApiItem _serviceItem;

        public ItemController(IServiceApiItem serviceItem)
        {
            _serviceItem = serviceItem;
        }

        public ActionResult Index(string id)
        {
            var request = Util.Decrypt(id).Split('|');
            IdList = int.Parse(request[0]);
            ViewBag.ListItems = _serviceItem.GetByLisItem(IdList);
            ViewBag.NomeLista = request[1];
            ViewBag.UserEmail = request[2];
            return View();
        }

        public ActionResult UpdatePositionItem(string items)
        {
            var listItem = _serviceItem.GetByLisItem(IdList);
            if (!string.IsNullOrEmpty(items))
            {
                var list = items.Split(",".ToCharArray(), StringSplitOptions.RemoveEmptyEntries).Select(int.Parse).ToArray();

                for (int i = 0; i < list.Length; i++)
                {
                    var item = listItem.Find(x => x.Id == list[i]);
                    if (item != null && item.Position != i)
                    {
                        item.Position = i;

                        _serviceItem.Update((UpdateItemRequest)item);
                    }
                }
            }

            return Json(true, JsonRequestBehavior.AllowGet);
        }

        public ActionResult UpdatePositionSubItem(string items)
        {
            var listItem = _serviceItem.GetByLisItem(IdList);
            if (!string.IsNullOrEmpty(items))
            {
                var list = items.Split(",".ToCharArray(), StringSplitOptions.RemoveEmptyEntries).ToArray();

                for (int i = 0; i < list.Length; i++)
                {
                    var itemMoved = list[i].Split('|').Select(int.Parse).ToArray();
                    var itemInList = listItem.Find(x => x.Id == itemMoved[0]);

                    if (itemInList != null &&
                        (itemInList.Position != i || (itemInList.Position == i && itemInList.IdParentItem != itemMoved[1])))
                    {
                        itemInList.Position = i;
                        itemInList.IdParentItem = itemMoved[1];

                        _serviceItem.Update((UpdateItemRequest)itemInList);
                    }
                }
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult SaveItem(string description, string itemId, string inptParentItemId, string buttonType)
        {
            var auxList = _serviceItem.GetByLisItem(IdList);

            if (buttonType.Equals("Save") || buttonType.Equals("Convert"))
            {
                if (string.IsNullOrEmpty(itemId))
                {
                    SaveItem(description, inptParentItemId, auxList);
                }
                else
                {
                    UpdateItem(description, itemId, buttonType, auxList);
                }
            }
            else
            {
                RemoveItem(itemId, auxList);
            }

            return PartialView("PartialItems", _serviceItem.GetByLisItem(IdList));
        }

        private void RemoveItem(string itemId, System.Collections.Generic.List<ItemResponse> auxList)
        {
            var items = auxList.Where(x => x.IdParentItem.ToString().Equals(itemId));

            foreach (var item in items)
            {
                _serviceItem.Remove(item.Id);
            }

            _serviceItem.Remove(int.Parse(itemId));
        }

        private void UpdateItem(string description, string itemId, string buttonType, System.Collections.Generic.List<ItemResponse> auxList)
        {
            var item = auxList.FirstOrDefault(x => x.Id.ToString().Equals(itemId));
            item.Description = description;

            if (buttonType.Equals("Convert") && item.IdParentItem != 0)
            {
                item.IdParentItem = null;
                item.Position = auxList.Count > 0 ? auxList.Where(x => x.IdParentItem == null || x.IdParentItem.Value == 0).Max(x => x.Position) + 1 : 0;
            }
            _serviceItem.Update((UpdateItemRequest)item);
        }

        private void SaveItem(string description, string inptParentItemId, System.Collections.Generic.List<ItemResponse> auxList)
        {
            var request = new InsertItemRequest() { Description = description, IdListItem = IdList };

            if (!string.IsNullOrEmpty(inptParentItemId))
            {
                request.IdParentItem = int.Parse(inptParentItemId);
                var parentItens = auxList.Where(x => x.IdParentItem != null &&
                                                      x.IdParentItem.Value.ToString() == inptParentItemId);
                request.Position = parentItens.Any() ? parentItens.Max(x => x.Position) + 1 : 0;
            }
            else
            {
                request.Position = auxList.Count > 0 ? auxList.Where(x => x.IdParentItem == null || x.IdParentItem.Value == 0)
                                                             .Max(x => x.Position) + 1 : 0;

            }

            _serviceItem.Insert(request);
        }

        [HttpPost]
        public ActionResult SendEmail(string email, string nomeLista, string userEmail)
        {
            try
            {
                string idEncrypt = Util.Encrypt(IdList.ToString() + "|" + nomeLista + "|" + userEmail);

                string url = string.Format("http://{0}/Item/Index/{1}", HttpContext.Request.Url.Authority, idEncrypt);
                Util.SendEmail(email, nomeLista, userEmail, url);

                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, erroMessage = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }


    }
}

ToDo/Views/Item/Index.cshtml
@using ToDo.Models.Arguments.Item

@{
    ViewBag.Title = "Items";
}
<div class="container">
    <div class="d-block">
        <a class="btn btn-info btn-round" href="/Home/About">
            <i class="material-icons">info</i> Sobre
        </a>
        <div class="btn-group">
            <a class="btn btn-primary btn-round" href="/Home/Index">
                <i class="material-icons">home</i> Início
            </a>
            <button class="btn btn-info btn-round" onclick="AddEditItem()">
                <i class="material-icons">add</i>  Adicione novo item
            </button>
            <button class="btn btn-success btn-round" onclick="OpenModalEmail()">
                <i class="material-icons">share</i>  Compartilhar lista
            </button>
        </div>
        <div>
            <h3 class="ml-4 d-inline" id="nomeLista">@ViewBag.NomeLista</h3><h5 class="ml-4 d-inline">Quem criou: <span id="userEmail">@ViewBag.UserEmail</span></h5>
        </div>
    </div>
    <div class="card-block" id="itemSortable">
        @Html.Partial("PartialItems", ViewBag.ListItems as List<ItemResponse>)
    </div>
</div>
@Html.Partial("PartialModalAddEditItem")
@Html.Partial("PartialModalShareEmail")

ToDo/Views/Item/PartialItems.cshtml
@model IEnumerable<ItemResponse>
@using ToDo.Models.Arguments.Item
<script>

    $(document).ready(function () {

        $("#itemSortable").sortable({
            placeholder: 'ui-state-highlight',
            revert: true,
            cancel: ".disable-item-sorting",
            opacity: 0.5,
            update: function (event, ui) {
                var items = "";
                $("#itemSortable").find(".item-card").each(function () {
                    var itemId = $(this).attr("data-item-id");
                    items = items + "," + itemId;
                });
                $.ajax({
                    url: '@Url.Action("UpdatePositionItem", "Item")',
                    data: { items: items },
                    type: 'POST',
                    success: function (data) {

                    },
                    error: function (xhr, status, error) {

                    }

                });
            }
        });

        $("div[id^='subItemsortable']").sortable({
            opacity: 0.5,
            revert: true,
            cancel: ".disable-sub-item-sorting",
            start: function (event, ui) {
            },
            update: function (event, ui) {
                var items = "";
                $("div[id*='subItemsortable']").find(".sub-item-card").each(function () {
                    var subItemId = $(this).attr("data-sub-item-id");
                    var item = $(this).closest(".item-card");
                    var itemId = "-1";
                    if (item.length > 0) {
                        itemId = item[0].getAttribute("data-item-id")
                    }
                    items = items + "," + subItemId + "|" + itemId;
                });

                $.ajax({
                    url: '@Url.Action("UpdatePositionSubItem", "Item")',
                    data: { items: items },
                    type: 'POST',
                    success: function (data) {

                    },
                    error: function (xhr, status, error) {

                    }
                });

            },
            stop: function (event, ui) {
            },
            receive: function (event, ui) {
            },
            connectWith: ".sortable"
        });

    });
</script>
@if (Model != null)
{
    foreach (var item in Model.Where(x => x.IdParentItem == null || x.IdParentItem.Value == 0))
    {
        <div class="card item-card" id="item@(item.Id)" data-item-id="@(item.Id)">
            <div class="card-header card-header-primary item-card-header">
                <labe id="descript@(item.Id)">@item.Description</labe>
            </div>
            <div class="edit-sub-item-card">
                <a href="#" class="disable-item-sorting btn btn-primary btn-sm btn-just-icon btn-fill btn-round btn-wd" onclick="AddEditItem(@item.Id,'','@item.Description')">
                    <i class="material-icons">mode_edit</i>
                </a>
            </div>
            <div id="subItemsortable@(item.Id)" class="disable-item-sorting card-body item-card-body sortable">
                @{
                    foreach (var subItem in Model.Where(x => x.IdParentItem != null && x.IdParentItem.Value == item.Id))
                    {
                        <div class="card sub-item-card" id="child@(subItem.Id)" data-sub-item-id="@(subItem.Id)">
                            <div class="card-body">
                                @subItem.Description
                            </div>
                            <div class="edit-sub-item-card">
                                <a href="#" class="disable-sub-item-sorting btn btn-primary btn-sm btn-just-icon btn-fill btn-round btn-wd" onclick="AddEditItem(@subItem.Id,@item.Id,'@subItem.Description')">
                                    <i class="material-icons">mode_edit</i>
                                </a>
                            </div>
                        </div>
                    }
                }

            </div>
            <div class="disable-item-sorting card-footer item-card-footer" onclick="AddEditItem('',@item.Id,'')">
                <span>+ Adicionar sub-item</span>
            </div>
        </div>
    }
}

ToDo/Views/Item/PartialModalAddEditItem.cshtml
@using (Ajax.BeginForm("SaveItem", "Item", new AjaxOptions() { UpdateTargetId = "itemSortable", InsertionMode = InsertionMode.Replace, HttpMethod = "POST" }))
{
    <div class="modal fade" id="addEditItemModal" tabindex="-1" role="dialog" aria-labelledby="itemModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="itemModalLabel"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="itemId" id="inptItemId" value="" />
                    <input type="hidden" name="inptParentItemId" id="inptParentItemId" value="" />
                    <div class="form-group">
                        <label for="inptDescription">Descrição</label>
                        <input type="text" name="description" class="form-control" placeholder="Insira a descrição" id="inptDescription">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default mr-1" onclick="CloseModal('addEditItemModal')" id="btnConvertItem" name="ButtonType" value="Convert">Converter para item principal</button>
                    <button type="submit" class="btn btn-primary mr-1" onclick="CloseModal('addEditItemModal')" id="btnSaveItem" name="ButtonType" value="Save">Salvar</button>
                    <button type="submit" class="btn btn-danger mr-1 d-none" onclick="CloseModal('addEditItemModal')" id="btnRemoveItem" name="ButtonType" value="Remove">Remover</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>
}

ToDo/Views/Item/PartialModalShareEmail.cshtml
<div class="modal fade" id="EmailModal" tabindex="-1" role="dialog" aria-labelledby="emailModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="emailModalLabel">Insira o e-mail que será enviado o link</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input type="text" name="email" class="form-control" placeholder="Email" id="inptEmail">
            </div>
            <h5 id="erroEmail"></h5>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary mr-1" onclick="SendEmail('@Url.Action("SendEmail", "Item")')" id="btnShareEmail">Compartilhar</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>